spring.application.name=demo-api-rest-java
spring.port=8085

#SQLite
spring.datasource.url=jdbc:sqlite:./data/demo-api-rest-java.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=never